services:
  delta-cosmetics:
    restart: always
    container_name: delta-cosmetics
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/var/www/html/         # Mount Yii2 web root
    ports:
      - "96:80"   # Map external port 96 to container's port 80
    networks:
      - shared

networks:
  shared:
    name: shared
    external: true